### ISSUE TITLE
Pls fix this bug.

### ISSUE THREAD

**Issue by OliseNS** [ultralytics/hub#1047]
> I am going through this same problem right now. It disconnects, and when I restart it, it is stuck on loading. This makes me not progress with my task, as I have to wake up and keep restarting
> 
> ![Image](https://github.com/user-attachments/assets/87d69619-2f01-4d94-afe6-6433ea5a751b) 

 _Originally posted by @OliseNS in [#588](https://github.com/ultralytics/hub/issues/588#issuecomment-2700132533)_

Also it keeps training while on the loading screen, pls fix this as I have a project presentation due soon.

**Comment by OliseNS** [comment]
I have problems with uploading big files too, i have 300,000 images for training but it uploads and gives me this error

![Image](https://github.com/user-attachments/assets/fd4af444-4c8b-48a1-be7b-cc7088cdbf05)

I even made sure to check the dataset before uploading using

from ultralytics.hub import check_dataset

check_dataset("augmezip.zip", task="detect")

 It doesn't upload and I've tried a couple times.

**Comment by sergiuwaxmann** [comment]
@OliseNS The current upload process encounters issues if there are connection problems on either end and does not have an automatic retry mechanism implemented. We will improve this in upcoming versions.

In the meantime, we will investigate on our end, but I recommend trying again with a stable internet connection.

**Comment by OliseNS** [comment]
> @OliseNS The current upload process encounters issues if there are connection problems on either end and does not have an automatic retry mechanism implemented. We will improve this in upcoming versions.
> 
> In the meantime, we will investigate on our end, but I recommend trying again with a stable internet connection.

Thanks. I left it in the timeout and got back to it later and it was fully uploaded meaning I don't have to retry again. I have a question though. How do I augment in Ultralytics hub because now I augment on my pc before uploading. Is there an inbuilt way in Ultralytics hub? because my pc is smoking just from augmentation 😂.

**Comment by pderrenger** [comment]
Hi @OliseNS,

Great question! Currently, **Ultralytics HUB** doesn't include built-in dataset augmentation features. The platform expects datasets to be uploaded in their final prepared format, as shown in our [Datasets documentation](https://docs.ultralytics.com/hub/datasets/). However, there's a smart solution:

You can **integrate augmentation directly into your training configuration** using YAML parameters. When you create a model in Ultralytics HUB, you can specify augmentation parameters in your training YAML like this:

```yaml
# Example augmentation parameters
augment: 
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7    # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4    # image HSV-Value augmentation (fraction)
  degrees: 15    # image rotation (+/- deg)
  translate: 0.1 # image translation (+/- fraction)
  scale: 0.5     # image scale (+/- gain)
  shear: 0.0     # image shear (+/- deg)
  perspective: 0.0001  # image perspective (+/- fraction)
  flipud: 0.0    # image flip up-down (probability)
  fliplr: 0.5    # image flip left-right (probability)
```

These augmentations will be applied **on-the-fly during training** using our cloud GPUs, which should give your local PC some relief! 😊

For more advanced control, you can:
1. Prepare your dataset YAML with custom augmentation parameters locally using our [YOLO training guide](https://docs.ultralytics.com/usage/cfg/#augmentation-parameters)
2. Validate it with `check_dataset()`
3. Upload the ZIP to HUB for cloud training

This approach lets you leverage our cloud resources for both augmentation and training while maintaining full control through your YAML configuration. Would you like me to elaborate on any specific aspect of this workflow?

**Comment by OliseNS** [comment]
> Hi @OliseNS,
> 
> Great question! Currently, **Ultralytics HUB** doesn't include built-in dataset augmentation features. The platform expects datasets to be uploaded in their final prepared format, as shown in our [Datasets documentation](https://docs.ultralytics.com/hub/datasets/). However, there's a smart solution:
> 
> You can **integrate augmentation directly into your training configuration** using YAML parameters. When you create a model in Ultralytics HUB, you can specify augmentation parameters in your training YAML like this:
> 
> ```yaml
> # Example augmentation parameters
> augment: 
>   hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
>   hsv_s: 0.7    # image HSV-Saturation augmentation (fraction)
>   hsv_v: 0.4    # image HSV-Value augmentation (fraction)
>   degrees: 15    # image rotation (+/- deg)
>   translate: 0.1 # image translation (+/- fraction)
>   scale: 0.5     # image scale (+/- gain)
>   shear: 0.0     # image shear (+/- deg)
>   perspective: 0.0001  # image perspective (+/- fraction)
>   flipud: 0.0    # image flip up-down (probability)
>   fliplr: 0.5    # image flip left-right (probability)
> ```
> 
> These augmentations will be applied **on-the-fly during training** using our cloud GPUs, which should give your local PC some relief! 😊
> 
> For more advanced control, you can:
> 1. Prepare your dataset YAML with custom augmentation parameters locally using our [YOLO training guide](https://docs.ultralytics.com/usage/cfg/#augmentation-parameters)
> 2. Validate it with `check_dataset()`
> 3. Upload the ZIP to HUB for cloud training
> 
> This approach lets you leverage our cloud resources for both augmentation and training while maintaining full control through your YAML configuration. Would you like me to elaborate on any specific aspect of this workflow?

Meaning I'll have 2 yaml files detect.yaml and config.yaml?

**Comment by pderrenger** [comment]
Hi @OliseNS,

Great follow-up question! You'll only need **one YAML file** that handles both dataset configuration and augmentation parameters. Here's the streamlined workflow:

1. **Single YAML Structure**: Your dataset YAML (e.g., `detect.yaml`) should contain both:
   - Dataset paths and class names (standard YOLO format)
   - Augmentation parameters (under the `augment:` key)

Example structure:
```yaml
# detect.yaml
path: ../datasets/my_dataset
train: images/train
val: images/val

names: 
  0: cat
  1: dog

# Augmentation section
augment:
  hsv_h: 0.1
  fliplr: 0.75
  mosaic: 1.0
```

2. **Validation**: Check this combined YAML with:
```python
from ultralytics.hub import check_dataset
check_dataset("detect.yaml", task="detect")
```

3. **Upload**: Zip this YAML with your dataset files and upload to Ultralytics HUB. When creating a new model, HUB will automatically detect and apply your augmentation parameters from the YAML.

This single-file approach keeps everything organized while letting you leverage cloud-based augmentation. For advanced configurations, see our [Training Configuration Guide](https://docs.ultralytics.com/usage/cfg) which shows how to combine dataset and training parameters in one file.

Let me know if you'd like help optimizing specific augmentation parameters for your 300k-image dataset! 🚀
