### ISSUE TITLE
Combining Two Datasets in YOLO

### ISSUE THREAD

**Issue by jaisenbe58r** [ultralytics/hub#754]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello Ultralytics Team,

I am currently working on a project using YOLO and I have two separate datasets that I would like to combine for training and validation purposes. I would like to know if it is possible to combine these datasets, and if so, how should I structure my `data.yml` file to properly reference both datasets?

### Example Details:
- **Dataset 1:**
  - Images: `/path/to/datasets/dataset1/images/`
  - Labels: `/path/to/datasets/dataset1/labels/`
- **Dataset 2:**
  - Images: `/path/to/datasets/dataset2/images/`
  - Labels: `/path/to/datasets/dataset2/labels/`

### Folder Structure:
```
/dataset/detect/
├── dataset1/
│   ├── images/
│   │   ├── train/
│   │   ├── val/
│   └── labels/
│       ├── train/
│       ├── val/
├── dataset2/
│   ├── images/
│   │   ├── train/
│   │   ├── val/
│   └── labels/
│       ├── train/
│       ├── val/
```

### Proposed `data.yml` Configuration:
```yaml
# File: data.yml

train: 
  - dataset1/images/train
  - dataset2/images/train
val: 
  - dataset1/images/val
  - dataset2/images/val

# Number of classes
nc: <number_of_classes>

# Class names
names: ['class1', 'class2', 'class3', ...]
```

Could you please confirm if this setup is correct and whether it is possible to combine datasets in this manner? If there are any additional steps or considerations I need to take into account, please let me know.

Thank you for your assistance!

Best regards,
Jaime

**Comment by sergiuwaxmann** [comment]
@jaisenbe58r Hello!
Unfortunately, the structure you suggested won't work... You need to create a new dataset using the structure we highlighted in [our documentation](https://docs.ultralytics.com/hub/datasets#upload-dataset).

**Comment by jaisenbe58r** [comment]
Hello @sergiuwaxman!,

That's unfortunate to hear. Thank you for your clarification and assistance.

Best regards,
Jaime.

**Comment by pderrenger** [comment]
Hello @jaisenbe58r,

Thank you for your understanding. To combine your datasets effectively, you can create a new dataset directory that includes the images and labels from both datasets. Here's a step-by-step guide to help you structure your combined dataset:

1. **Create a New Directory**: Create a new directory, say `combined_dataset/`, and within it, create subdirectories for `images/train`, `images/val`, `labels/train`, and `labels/val`.

2. **Merge Images and Labels**: Copy the images and labels from both datasets into the respective subdirectories of `combined_dataset/`.

3. **Update the YAML File**: Create a new YAML file for the combined dataset. Here's an example configuration:

```yaml
# File: combined_dataset.yaml

path: ../datasets/combined_dataset  # root directory of the combined dataset
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Number of classes
nc: <number_of_classes>

# Class names
names: ['class1', 'class2', 'class3', ...]
```

4. **Validate the Dataset**: Before uploading to Ultralytics HUB, validate your dataset to ensure it's correctly formatted:

```python
from ultralytics.hub import check_dataset

check_dataset("path/to/combined_dataset.zip", task="detect")
```

5. **Upload to Ultralytics HUB**: Zip the `combined_dataset/` directory and upload it to Ultralytics HUB following the instructions in our [documentation](https://docs.ultralytics.com/hub/datasets#upload-dataset).

By following these steps, you can seamlessly combine your datasets and utilize them for training and validation.

If you encounter any issues or need further assistance, feel free to reach out. We're here to help!

**Comment by jaisenbe58r** [comment]
Hello @pderrenger,

Thank you for the detailed explanation and the step-by-step guide on combining the datasets. It is very helpful.

I have a follow-up question: Is there no way to structure the `data.yml` file by adding multiple paths for the images, something like this?

```yaml
# File: combined_dataset.yaml

path: ../datasets/combined_dataset  # root directory of the combined dataset
train: 
  - dataset1/images/train
  - dataset2/images/train
val: 
  - dataset1/images/val
  - dataset2/images/val

# Number of classes
nc: <number_of_classes>

# Class names
names: ['class1', 'class2', 'class3', ...]
```

Would this approach not be possible or supported by the Ultralytics framework? It would be more convenient to maintain the original datasets separately.

Thank you again for your assistance!

Best regards,
Jaime.

**Comment by pderrenger** [comment]
Hello @jaisenbe58r,

Thank you for your kind words and for the follow-up question!

Currently, the Ultralytics framework does not support specifying multiple paths for the `train` and `val` directories directly within the `data.yaml` file. The framework expects a single path for each of these entries. Therefore, the approach you suggested would not work as intended.

To maintain the original datasets separately while still combining them for training, you can use symbolic links (symlinks) to create a unified directory structure without duplicating the data. Here's how you can do it:

1. **Create a New Directory**: Create a new directory, say `combined_dataset/`, and within it, create subdirectories for `images/train`, `images/val`, `labels/train`, and `labels/val`.

2. **Create Symlinks**: Use symlinks to link the images and labels from both datasets into the respective subdirectories of `combined_dataset/`. Here’s an example of how to create symlinks in a Unix-based system:

```bash
# Create symlinks for training images
ln -s /path/to/datasets/dataset1/images/train/* /path/to/combined_dataset/images/train/
ln -s /path/to/datasets/dataset2/images/train/* /path/to/combined_dataset/images/train/

# Create symlinks for validation images
ln -s /path/to/datasets/dataset1/images/val/* /path/to/combined_dataset/images/val/
ln -s /path/to/datasets/dataset2/images/val/* /path/to/combined_dataset/images/val/

# Create symlinks for training labels
ln -s /path/to/datasets/dataset1/labels/train/* /path/to/combined_dataset/labels/train/
ln -s /path/to/datasets/dataset2/labels/train/* /path/to/combined_dataset/labels/train/

# Create symlinks for validation labels
ln -s /path/to/datasets/dataset1/labels/val/* /path/to/combined_dataset/labels/val/
ln -s /path/to/datasets/dataset2/labels/val/* /path/to/combined_dataset/labels/val/
```

3. **Update the YAML File**: Use the same YAML configuration as before, pointing to the `combined_dataset/` directory:

```yaml
# File: combined_dataset.yaml

path: ../datasets/combined_dataset  # root directory of the combined dataset
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Number of classes
nc: <number_of_classes>

# Class names
names: ['class1', 'class2', 'class3', ...]
```

This way, you can maintain the original datasets separately while creating a unified structure for training purposes.

If you have any further questions or need additional assistance, feel free to ask. We're here to help!
